In [17]:
# Import necessary libraries
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime, timedelta

# Create database connection
# Replace these with your actual database credentials
db_connection_string = 'postgresql://default:rz5dBTWh0kbF@ep-cool-haze-a42pervx-pooler.us-east-1.aws.neon.tech/verceldb?sslmode=require'
engine = create_engine(db_connection_string)

# Define the date you want to query
# target_date = datetime(2024, 3, 20).date() # or specify a specific date: datetime(2024, 3, 20).date()

# SQL query to fetch one day of data
query = f"""
SELECT o.*
FROM observations o
WHERE o.station_id = (
SELECT s.id
FROM stations s
WHERE s.station_name = 'Mt. Baker - Heather Meadows'
)
AND o.date_time >= '2025-03-27 00:00:00+00'
AND o.date_time < '2025-03-28 00:00:00+00'
ORDER BY o.date_time DESC 
"""

# Execute query and load into pandas DataFrame
df = pd.read_sql(query, engine)

# Display the first few rows of the data
df.head()

# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              24 non-null     int64
 1   station_id                      24 non-null     object
 2   date_time                       24 non-null     datetime64[ns, UTC]
 3   air_temp                        24 non-null     float64
 4   snow_depth                      24 non-null     float64
 5   snow_depth_24h                  24 non-null     float64
 6   precip_accum_one_hour           24 non-null     float64
 7   relative_humidity               24 non-null     float64
 8   battery_voltage                 0 non-null      object
 9   intermittent_snow               0 non-null      object
 10  precipitation                   0 non-null      object
 11  wind_speed                      0 non-null      object
 12  wind_speed_min                  0 non-null      object
 13  wind_gust                       0 non-null      object
 14  wind_direction                  0 non-null      object
 15  solar_radiation                 0 non-null      object
 16  equip_temperature               0 non-null      object
 17  pressure                        0 non-null      object
 18  wet_bulb                        0 non-null      object
 19  soil_temperature_a              0 non-null      object
 20  soil_temperature_b              0 non-null      object
 21  soil_moisture_a                 0 non-null      object
 22  soil_moisture_b                 0 non-null      object
 23  soil_temperature_c              0 non-null      object
 24  soil_moisture_c                 0 non-null      object
 25  api_fetch_time                  24 non-null     datetime64[ns, UTC]
 26  error_filtered_total_snow       0 non-null      object
 27  error_filtered_24hr_snow_accum  0 non-null      object
dtypes: datetime64[ns, UTC](2), float64(5), int64(1), object(20)
memory usage: 5.4+ KB

In [19]:
print("First 5 rows of the data:")
display(df.head())

First 5 rows of the data:

,id,station_id,date_time,air_temp,snow_depth,snow_depth_24h,precip_accum_one_hour,relative_humidity,battery_voltage,intermittent_snow,...,wet_bulb,soil_temperature_a,soil_temperature_b,soil_moisture_a,soil_moisture_b,soil_temperature_c,soil_moisture_c,api_fetch_time,error_filtered_total_snow,error_filtered_24hr_snow_accum
0,21242542,b87db03b-738b-4308-9243-ea24c8788f8b,2025-03-27 23:00:00+00:00,4.81,378.71,0.41,0.0,66.67,None,None,...,None,None,None,None,None,None,None,2025-03-28 00:20:19.086331+00:00,None,None
1,21241918,b87db03b-738b-4308-9243-ea24c8788f8b,2025-03-27 22:00:00+00:00,4.53,378.97,0.07,0.0,69.03,None,None,...,None,None,None,None,None,None,None,2025-03-27 22:05:16.783637+00:00,None,None
2,21241682,b87db03b-738b-4308-9243-ea24c8788f8b,2025-03-27 21:00:00+00:00,4.56,378.46,-0.10,0.0,69.76,None,None,...,None,None,None,None,None,None,None,2025-03-27 21:05:17.168458+00:00,None,None
3,21241772,b87db03b-738b-4308-9243-ea24c8788f8b,2025-03-27 20:00:00+00:00,4.47,378.46,-0.44,0.0,73.85,None,None,...,None,None,None,None,None,None,None,2025-03-27 21:05:19.766983+00:00,None,None
4,21241057,b87db03b-738b-4308-9243-ea24c8788f8b,2025-03-27 19:00:00+00:00,2.96,378.46,-0.14,0.0,79.64,None,None,...,None,None,None,None,None,None,None,2025-03-27 19:05:16.498168+00:00,None,None